#!/usr/bin/env python3
"""
render_flowchart.py

Converts a Flow_Chart_Process.md file (containing Mermaid diagrams)
into a self-contained, browser-ready HTML file.

Usage:
    python render_flowchart.py <path/to/Flow_Chart_Process.md>
    python render_flowchart.py <path/to/Flow_Chart_Process.md> --output <path/to/output.html>

Output:
    Flow_Chart_Process.html in the same directory as the input file (default),
    or at the specified --output path.
"""

import sys
import re
import argparse
from pathlib import Path


GANTT_ONLY_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #f5f6fa;
      color: #2d3148;
      margin: 0;
      padding: 0;
    }}
    header {{
      background: #1e1f2e;
      color: #fff;
      padding: 24px 40px;
      border-bottom: 3px solid #4f5bd5;
    }}
    header h1 {{
      margin: 0 0 4px 0;
      font-size: 1.6rem;
      font-weight: 700;
      letter-spacing: -0.01em;
    }}
    header p {{
      margin: 0;
      font-size: 0.85rem;
      color: #9899b0;
    }}
    .container {{
      max-width: 1400px;
      margin: 0 auto;
      padding: 40px;
    }}
    .chart-card {{
      background: #fff;
      border: 1px solid #e2e4ef;
      border-radius: 10px;
      padding: 36px;
      overflow-x: auto;
    }}
    .mermaid {{
      display: flex;
      justify-content: center;
      min-height: 80px;
    }}
    .mermaid svg {{
      max-width: 100%;
      height: auto;
    }}
    footer {{
      text-align: center;
      padding: 24px;
      color: #9899b0;
      font-size: 0.8rem;
      border-top: 1px solid #e2e4ef;
      margin-top: 20px;
    }}
  </style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <p>Generated from <code>{source_file}</code> &mdash; Gantt chart view &mdash; open in any browser, no plugins required</p>
  </header>
  <div class="container">
    <div class="chart-card">
      {charts_html}
    </div>
  </div>
  <footer>
    Generated by render_flowchart.py &bull; business-module-workflow skill
  </footer>
  <script>
    mermaid.initialize({{
      startOnLoad: true,
      theme: 'default',
      gantt: {{ useMaxWidth: true, useWidth: 1200 }},
      themeVariables: {{
        primaryColor: '#4f5bd5',
        primaryTextColor: '#2d3148',
        primaryBorderColor: '#3d4ac4',
        lineColor: '#6b7280',
        secondaryColor: '#f0f1f8',
        tertiaryColor: '#fafbff',
      }}
    }});
  </script>
</body>
</html>
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; }}

    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #f5f6fa;
      color: #2d3148;
      margin: 0;
      padding: 0;
    }}

    header {{
      background: #1e1f2e;
      color: #fff;
      padding: 24px 40px;
      border-bottom: 3px solid #4f5bd5;
    }}

    header h1 {{
      margin: 0 0 4px 0;
      font-size: 1.6rem;
      font-weight: 700;
      letter-spacing: -0.01em;
    }}

    header p {{
      margin: 0;
      font-size: 0.85rem;
      color: #9899b0;
    }}

    .container {{
      max-width: 1200px;
      margin: 0 auto;
      padding: 32px 40px;
    }}

    .toc {{
      background: #fff;
      border: 1px solid #e2e4ef;
      border-radius: 10px;
      padding: 20px 28px;
      margin-bottom: 36px;
    }}

    .toc h2 {{
      font-size: 0.75rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: #9899b0;
      margin: 0 0 12px 0;
    }}

    .toc ol {{
      margin: 0;
      padding-left: 20px;
    }}

    .toc li {{
      margin: 6px 0;
    }}

    .toc a {{
      color: #4f5bd5;
      text-decoration: none;
      font-size: 0.95rem;
    }}

    .toc a:hover {{
      text-decoration: underline;
    }}

    .diagram-section {{
      background: #fff;
      border: 1px solid #e2e4ef;
      border-radius: 10px;
      margin-bottom: 28px;
      overflow: hidden;
    }}

    .diagram-header {{
      padding: 16px 28px;
      border-bottom: 1px solid #e2e4ef;
      background: #fafbff;
      display: flex;
      align-items: center;
      gap: 12px;
    }}

    .diagram-number {{
      background: #4f5bd5;
      color: #fff;
      font-size: 0.75rem;
      font-weight: 700;
      border-radius: 50%;
      width: 24px;
      height: 24px;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }}

    .diagram-header h2 {{
      margin: 0;
      font-size: 1.05rem;
      font-weight: 600;
      color: #2d3148;
    }}

    .diagram-body {{
      padding: 28px;
      overflow-x: auto;
    }}

    .prose-block {{
      padding: 12px 28px;
      color: #555870;
      font-size: 0.92rem;
      line-height: 1.65;
      border-bottom: 1px solid #f0f1f8;
    }}

    .prose-block p {{ margin: 6px 0; }}
    .prose-block ul, .prose-block ol {{ margin: 6px 0; padding-left: 22px; }}
    .prose-block li {{ margin: 4px 0; }}
    .prose-block code {{
      background: #f0f1f8;
      padding: 1px 5px;
      border-radius: 4px;
      font-size: 0.88em;
    }}

    .mermaid {{
      display: flex;
      justify-content: center;
      min-height: 80px;
    }}

    .mermaid svg {{
      max-width: 100%;
      height: auto;
    }}

    .render-error {{
      background: #fff5f5;
      border: 1px solid #fca5a5;
      border-radius: 6px;
      padding: 12px 16px;
      color: #dc2626;
      font-size: 0.85rem;
    }}

    footer {{
      text-align: center;
      padding: 24px;
      color: #9899b0;
      font-size: 0.8rem;
      border-top: 1px solid #e2e4ef;
      margin-top: 20px;
    }}
  </style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <p>Generated from <code>{source_file}</code> &mdash; open in any browser, no plugins required</p>
  </header>

  <div class="container">
    {toc_html}
    {sections_html}
  </div>

  <footer>
    Generated by render_flowchart.py &bull; business-module-workflow skill
  </footer>

  <script>
    mermaid.initialize({{
      startOnLoad: true,
      theme: 'default',
      flowchart: {{ curve: 'basis', useMaxWidth: true }},
      sequence: {{ useMaxWidth: true }},
      themeVariables: {{
        primaryColor: '#4f5bd5',
        primaryTextColor: '#2d3148',
        primaryBorderColor: '#3d4ac4',
        lineColor: '#6b7280',
        secondaryColor: '#f0f1f8',
        tertiaryColor: '#fafbff',
      }}
    }});
  </script>
</body>
</html>
"""


def slugify(text):
    """Convert heading text to a URL-safe anchor id."""
    text = text.lower().strip()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_-]+', '-', text)
    return text.strip('-')


def parse_md(md_text):
    """
    Parse the markdown into a list of sections, each being:
      { 'heading': str, 'level': int, 'blocks': [ ('prose'|'mermaid', content) ] }
    """
    lines = md_text.splitlines()
    sections = []
    current_section = None
    in_mermaid = False
    mermaid_lines = []
    prose_lines = []

    def flush_prose():
        if current_section is not None and prose_lines:
            stripped = '\n'.join(prose_lines).strip()
            if stripped:
                current_section['blocks'].append(('prose', stripped))
        prose_lines.clear()

    def flush_mermaid():
        if current_section is not None and mermaid_lines:
            current_section['blocks'].append(('mermaid', '\n'.join(mermaid_lines).strip()))
        mermaid_lines.clear()

    for line in lines:
        if in_mermaid:
            if line.strip() == '```':
                flush_mermaid()
                in_mermaid = False
            else:
                mermaid_lines.append(line)
            continue

        heading_match = re.match(r'^(#{1,4})\s+(.*)', line)
        if heading_match:
            flush_prose()
            level = len(heading_match.group(1))
            heading_text = heading_match.group(2).strip()
            current_section = {'heading': heading_text, 'level': level, 'blocks': []}
            sections.append(current_section)
            continue

        if line.strip().startswith('```mermaid'):
            flush_prose()
            in_mermaid = True
            continue

        if line.strip().startswith('```'):
            # Non-mermaid code block — treat as prose
            prose_lines.append(line)
            continue

        if current_section is not None:
            prose_lines.append(line)

    flush_prose()
    return sections


def prose_to_html(prose):
    """Very lightweight prose → HTML converter (no external deps)."""
    html_lines = []
    in_list = False
    in_ol = False

    def close_list():
        nonlocal in_list, in_ol
        if in_list:
            html_lines.append('</ul>')
            in_list = False
        if in_ol:
            html_lines.append('</ol>')
            in_ol = False

    lines = prose.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]

        # Unordered list
        ul_match = re.match(r'^[-*]\s+(.*)', line)
        if ul_match:
            if not in_list:
                close_list()
                html_lines.append('<ul>')
                in_list = True
            html_lines.append(f'<li>{inline_format(ul_match.group(1))}</li>')
            i += 1
            continue

        # Ordered list
        ol_match = re.match(r'^\d+\.\s+(.*)', line)
        if ol_match:
            if not in_ol:
                close_list()
                html_lines.append('<ol>')
                in_ol = True
            html_lines.append(f'<li>{inline_format(ol_match.group(1))}</li>')
            i += 1
            continue

        close_list()

        if line.strip() == '':
            i += 1
            continue

        html_lines.append(f'<p>{inline_format(line)}</p>')
        i += 1

    close_list()
    return '\n'.join(html_lines)


def inline_format(text):
    """Apply inline Markdown formatting: bold, italic, code, links."""
    # Code
    text = re.sub(r'`([^`]+)`', r'<code>\1</code>', text)
    # Bold
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    # Italic
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    # Links
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', text)
    return text


def build_html(sections, source_file):
    """Build the full HTML from parsed sections."""
    title = sections[0]['heading'] if sections else source_file

    # Build TOC from h2 sections only
    toc_items = []
    diagram_count = 0
    for s in sections:
        if s['level'] == 2:
            diagram_count += 1
            anchor = slugify(s['heading'])
            toc_items.append(
                f'<li><a href="#{anchor}">{s["heading"]}</a></li>'
            )

    toc_html = ''
    if toc_items:
        toc_html = (
            '<div class="toc">'
            '<h2>Diagrams in this document</h2>'
            '<ol>' + '\n'.join(toc_items) + '</ol>'
            '</div>'
        )

    # Build sections
    section_htmls = []
    diagram_idx = 0

    for s in sections:
        anchor = slugify(s['heading'])

        if s['level'] == 1:
            # Top-level heading — skip (already in header)
            continue

        if s['level'] == 2:
            diagram_idx += 1
            header_html = (
                f'<div class="diagram-header">'
                f'<div class="diagram-number">{diagram_idx}</div>'
                f'<h2 id="{anchor}">{s["heading"]}</h2>'
                f'</div>'
            )
            block_html = build_blocks(s['blocks'])
            section_htmls.append(
                f'<div class="diagram-section">{header_html}{block_html}</div>'
            )
        else:
            # h3/h4 — render as a smaller subsection inside a card
            block_html = build_blocks(s['blocks'])
            section_htmls.append(
                f'<div class="diagram-section">'
                f'<div class="diagram-header"><h2 id="{anchor}" style="font-size:0.95rem">'
                f'{s["heading"]}</h2></div>'
                f'{block_html}</div>'
            )

    sections_html = '\n'.join(section_htmls)

    return HTML_TEMPLATE.format(
        title=title,
        source_file=source_file,
        toc_html=toc_html,
        sections_html=sections_html,
    )


def build_blocks(blocks):
    html = ''
    for kind, content in blocks:
        if kind == 'prose':
            html += f'<div class="prose-block">{prose_to_html(content)}</div>'
        elif kind == 'mermaid':
            escaped = content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            html += (
                f'<div class="diagram-body">'
                f'<div class="mermaid">{escaped}</div>'
                f'</div>'
            )
    return html


def extract_gantt_blocks(md_text):
    """Extract only gantt diagram blocks from markdown text."""
    gantt_blocks = []
    lines = md_text.splitlines()
    in_mermaid = False
    is_gantt = False
    current_block = []

    for line in lines:
        if not in_mermaid:
            if line.strip().startswith('```mermaid'):
                in_mermaid = True
                is_gantt = False
                current_block = []
            continue

        # Inside a mermaid block
        if line.strip() == '```':
            if is_gantt and current_block:
                gantt_blocks.append('\n'.join(current_block).strip())
            in_mermaid = False
            current_block = []
        else:
            current_block.append(line)
            if line.strip().lower().startswith('gantt'):
                is_gantt = True

    return gantt_blocks


def build_gantt_only_html(gantt_blocks, source_file, title=None):
    """Build a chart-only HTML page containing just the Gantt diagrams."""
    if not title:
        title = Path(source_file).stem.replace('_', ' ').replace('-', ' ').title() + ' — Gantt Chart'

    charts_html_parts = []
    for block in gantt_blocks:
        charts_html_parts.append(f'<div class="mermaid">{block}</div>')

    charts_html = '\n'.join(charts_html_parts) if charts_html_parts else '<p style="color:#9899b0">No Gantt diagrams found in source file.</p>'

    return GANTT_ONLY_TEMPLATE.format(
        title=title,
        source_file=source_file,
        charts_html=charts_html,
    )


def main():
    parser = argparse.ArgumentParser(
        description='Render Flow_Chart_Process.md to a self-contained HTML file.'
    )
    parser.add_argument('input', help='Path to Flow_Chart_Process.md')
    parser.add_argument('--output', help='Output HTML path (default: same dir as input)')
    parser.add_argument(
        '--gantt-only',
        action='store_true',
        help='Extract and render only Gantt diagram blocks (ignores all other content)',
    )
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    if not input_path.exists():
        print(f'Error: file not found: {input_path}', file=sys.stderr)
        sys.exit(1)

    md_text = input_path.read_text(encoding='utf-8')

    if args.gantt_only:
        gantt_blocks = extract_gantt_blocks(md_text)
        if not gantt_blocks:
            print('Warning: no Gantt diagrams found in the markdown file.', file=sys.stderr)
        html = build_gantt_only_html(gantt_blocks, input_path.name)
    else:
        sections = parse_md(md_text)
        if not sections:
            print('Warning: no sections found in the markdown file.', file=sys.stderr)
        html = build_html(sections, input_path.name)

    if args.output:
        output_path = Path(args.output).resolve()
    else:
        output_path = input_path.with_suffix('.html')

    output_path.write_text(html, encoding='utf-8')
    print(f'✅ Rendered: {output_path}')
    print(f'   Open in any browser — no server or plugins required.')


if __name__ == '__main__':
    main()
